import styles from './TodasInvestigaciones.module.css';

const Nota11 = () => {
return(
<>
<p>Al caer el sol detrás de la autopista 25 de Mayo, en la Ciudad de Buenos Aires, el paisaje de tránsito pesado que inunda las calles durante el día, merma para dar lugar a lo invisible, a lo que a nadie parece importarle. Constitución es de los barrios más transitados. Miles de personas llegan hasta ahí desde distintos puntos del conurbano sur para comenzar el día laboral en la capital, la ciudad más rica del país. 
La autopista, que corre en paralelo a la avenida San Juan, separa dos mundos y aparece como un umbral. Hacia el norte, por avenida Independencia, la facultad de Ciencias Sociales de la UBA, la Universidad Argentina de la Empresa (UADE) y el Correo Argentino (y otros locales de concurrencia), tiñen el aire de un tamiz institucional y protegido. Allí el tránsito de gente parece seguro, cuidado por un frenesí social. Pero hacia el sur de la autopista, para el lado de la avenida Garay, sin importar la hora del día, hay un barrio librado a su suerte donde, incluso, una cama en donde pasar la noche es territorio de disputa. </p>

<p>En la Ciudad de Buenos Aires, hay miles de personas que no son propietarias pero que tampoco cumplen con los requisitos mínimos para pagar el alquiler mensual de una vivienda. La mayoría vive en hoteles familiares, como esos que abundan en Constitución, un entramado complejo donde se teje pobreza, zona liberada, narcomenudeo y administradores fantasmas.</p>

<h6 className={styles.span}>En la Ciudad de Buenos Aires, hay miles de personas que no son propietarias pero que tampoco cumplen con los requisitos mínimos para pagar el alquiler mensual de una vivienda. La mayoría vive en hoteles familiares, como esos que abundan en Constitución.</h6>

<h3 className={styles.subTitle}>De hotelados a subsidiados</h3>

<p>Las dos grandes políticas públicas que lleva adelante el GCBA ante la gran cantidad de personas situación de calle son los famosos “paradores” o Centros de Inclusión Social, de los cuales la propia gente se escapa por sus malas condiciones y sus lógicas “de penal” más que de acompañamiento. Sobre este tema, puede leerse la investigación publicada por el Mapa de la Policía acerca de las personas en situación de calle. La otra política es el subsidio habitacional 690, que se otorga a la gente que puede acreditar su situación de vulnerabilidad.</p>

<p>Los dos programas están bajo la órbita del ministerio de Desarrollo Humano y Hábitat de CABA. Sin embargo, no existe información oficial que permita dimensionar la cantidad de personas incluidas en ellos. El ministerio no provee cifras exactas y no posee un registro sistematizado. No obstante, según publicó El Grito del Sur en junio de 2022, del total de 243.245 personas alcanzadas por la ayuda estatal porteña, unas 18.625 cobraban esta ayuda social. “Ese subsidio se arma para desarmar el programa de hoteles, que se le decía de hotelados. El gobierno de la Ciudad contrataba directamente el hotel y le daba el alojamiento a la persona”, dice Carolina Sticotti, militante social y trabajadora del Centro de Salud Nivel 1 (Cesac) N°41 del barrio de La Boca. En el año 2006, por decreto 690/06, el Jefe de Gobierno de la CABA sancionó un programa para la atención de familias en situación de calle. Concretó, mediante éste, el cierre del programa de “hotelados”, derogando el decreto 895/02 y modificó la forma en que se venía ejecutando el programa existente. A partir de allí, la transferencia de dinero se hace directamente a las personas inscriptas. Al respecto, Sticotti, que acompaña a personas en procesos de desalojos desde hace 10 años, dice: “Como empezó a haber quilombos y se querían despegar legalmente de lo que pasaba ahí adentro (de los hoteles), el GCBA genera otro programa para desarmar el anterior. Pero lo único que hace es subsidiar un eterno problema de vivienda, y cronificarlo”. Para Sticotti, el subsidio 690 contribuye a que la situación vulnerable de la persona, en cuanto al acceso a la vivienda, se vuelva estructural, reafirma su pobreza, y garantiza que la gente viva en condiciones pésimas. “Definitivamente no quieren solucionar el problema. En vez de subsidiar el alquiler se podría subsidiar la compra”, sugiere.</p>

<p>Asimismo, cuenta que las personas desalojadas del barrio de La Boca terminan, en muchos casos, en uno de estos hoteles que pululan en los barrios más populares. “Otro tema es que en Desarrollo Humano y Hábitat dicen que hasta que la gente no esté en la calle no le pueden dar el subsidio – explica-  y entonces, en vez de evitar que la gente termine en la calle y pagarle antes para con eso ir buscando una solución… no, cuando te desalojen vení a pedir el subsidio. Hasta que no estés en la lona no te ayudo”.</p>

<p>Natalia, compañera de Carolina y referente social del barrio de La Boca, asegura que si a alguien le sirve esta modalidad (de subsidio) es al negocio de los desarrolladores inmobiliarios. El extractivismo del suelo y su revalorización para la especulación está a la orden del día. Existe, para ella, un proceso de gentrificación en ese territorio que ya lleva años. “Para que todo funcione de forma aceitada les conviene mantener a la gente en estas condiciones”, dice.</p>

<h6 className={styles.span}>Las dos grandes políticas que lleva adelante el GCBA ante la gran cantidad de personas situación de calle son los famosos “paradores” o Centros de Inclusión Social, de los cuales la propia gente se escapa por sus malas condiciones y sus lógicas “de penal” más que de acompañamiento. </h6>

 

<h3 className={styles.subTitle}>La burocracia del 690</h3>


<p>El subsidio 690 es un aporte económico que se otorga para pagar una habitación. Al momento de esta publicación, es de $ 35.000. Para obtenerlo hay que demostrar “desamparo habitacional” inminente o estar en situación de calle. Entre la documentación solicitada por el GCBA en su web, debe adjuntarse un informe social sobre del estado de vulnerabilidad que tiene la persona o familia, elaborado por el programa Buenos Aires Presente (BAP). Pero no solo eso, sino que la persona sin vivienda tiene que adjuntar un presupuesto ya sea con firma, copia de DNI y la boleta de un servicio del dueño directo que le alquilaría el lugar o un “documento membretado” del hotel disponible. De forma reciente, además, se sumó otro requisito: la persona en situación de calle debe hacer una rendición del subsidio cargando en la web la factura del hotel o un documento con la firma, DNI y CUIT del dueño.</p>

<p>Hugo Altamirano es trabajador de una carpintería cooperativa llamada “La Astilla”, ubicada en el barrio de Barracas. Complementa su trabajo allí haciendo delivery mediante plataformas digitales. Vive, desde que salió de la cárcel, de hotel en hotel. Pasó por tres diferentes en el barrio de Constitución pero eligió cambiar de barrio porque estaba “permanentemente tentado” por el consumo y el crimen organizado.</p>

<p>El problema, para él, no era conseguir el recibo de un hotel, sabía que si necesitaba podía hablarle a un contacto que los vendía en la plaza Garay. Luego de muchos intentos, había logrado llegar a un hotel en el barrio de Once donde estaba relativamente tranquilo.</p>

<p>Ahora, sin embargo, la preocupación por su inestabilidad habitacional ha reaparecido. Junto al recibo que acredita el hotel en el que vive, además del informe del trabajador social que da cuenta de su situación de vulnerabilidad, es necesario que entregue al GCBA una fotocopia del DNI del dueño del hotel. Los dueños de los hoteles dispuestos a dar esa información son contados con los dedos de las manos. El del hotel donde está Hugo, en la calle Moreno al 2400, no está dispuesto a brindarle esa información.</p>

<p>Lleva ya más de dos meses sin cobrar el subsidio y en la sede del ministerio de Desarrollo Humano y Hábitat, ubicada en las calles Pavón y Entre Ríos, le dicen que deben ir a verificar su vivienda y hablar con el encargado del hotel para asegurarse de que realmente esté viviendo donde acredita. Pero pasan en vano las semanas y las fechas en que le prometen que lo visitarán. Nunca lo hacen. “Nos acostumbramos a vivir mal”.</p>

<h6 className={styles.span}>La preocupación por su inestabilidad habitacional ha reaparecido. Junto al recibo que acredita el hotel en el que vive, es necesario que entregue al GCBA una fotocopia del DNI del dueño del hotel. Los dueños de los hoteles dispuestos a dar esa información son contados con los dedos de las manos.</h6>

<h3 className={styles.subTitle}>Vivir en un búnker</h3>


<p>Cuando llegó el operativo policial hacía ya tiempo que Oscar Cabañes, de 62 años,  utilizaba un hotel ubicado en la calle Santiago del Estero al 1200 (donde también vivía) como base de operaciones logísticas para su trabajo: venta, corte, consumo, cocina y banco de cocaína. El inmueble, al mismo tiempo, albergaba como vivienda a una cantidad incontable de personas: madres solas con sus hijos, gente por fuera de las lógicas del mundo del trabajo, algunos sin documentos y al borde de quedarse en la calle, bandidos urbanos de poca monta -y no tanto-, trabajadores hiper precarizados, mujeres en redes de trata, etcétera. Unos días antes, un cronista de Canal A24 había hecho público un punto de venta de sustancias en el barrio de Once, un búnker. El notero se había acercado a pedir que le vendieran cocaína mientras filmaba a escondidas la secuencia. Esto derivó en un gran operativo policial en el barrio de Constitución en el cual se allanaron más de 20 búnkeres. Se detuvo, en esa ocasión, a más de 30 personas –entre ellas a Oscar- por narcomenudeo e incautaron más de 2 millones de pesos y 730 dosis de cocaína. Cabañes era adicto al crac, a la heroína y a la cocaína. También a lo que le hicieron creer. En el barrio lo conocían todos, aunque no todos lo querían: “Ese viejo no es transa, es soldadito nada más. Los dueños del hotel lo obligan a vender y medio Constitución lo odia porque trata mal a los pibes a los que le vende falopa”, comenta Walter, un eterno deambulante en situación de calle que a veces está en La Boca y otras en Constitución.</p>

<p>Cayó preso, al alba, el jueves 13 de Julio de 2023. Consigo, 30 colegas más destinados a vender cocaína y sus derivados por las calles del barrio. La cicatriz de Oscar, dibujada por hilos de cocer, se la había ganado en la comisaría, aunque, al igual que los restantes vendedores, conoció el encierro solo por una noche. La fiscalía ordenó su libertad a pocas horas de ser detenido. Me muestra el expediente de su causa donde se lo ve en fotos, en la puerta del hotel. También aparecen imágenes de 50 bolsas de 1 gramo de cocaína (con un valor de mil pesos cada una) y fotos de billetes arrugados de 20 pesos que tenía al momento de la detención. El resto de la plata, cuenta, estaba dividida: una parte en las paredes de su habitación que encontraron de forma “extraoficial”; y otra parte en una cocina que nunca revisaron. Estaba libre pero esa libertad se parecía más a la de un sentenciado a la desesperanza.</p>

<h6 className={styles.span}>Cuando llegó el operativo policial hacía ya tiempo que Oscar Cabañes  utilizaba un hotel ubicado en la calle Santiago del Estero al 1200 (donde también vivía) como base de operaciones logísticas para su trabajo: venta, corte, consumo, cocina y banco de cocaína.</h6>

<h3 className={styles.subTitle}>Postales de un hacinamiento perfecto</h3>


<p>Si bien es explícita la degradación de los hoteles del barrio Constitución, a lo largo de la presente investigación, su estructura de poder se ha mantenido en la oscuridad: los dueños de los hoteles parecen fantasmas. Algunas averiguaciones muestran que los propietarios fueron, mayormente, migrantes italianos o españoles que al morir dejaron desocupados los inmuebles, usufructuados luego de diversas formas. Según los datos recabados por el Mapa de la Policía entre inquilinos y vecinos del barrio, ante la figura abstracta de los propietarios, emergen otros protagonistas: los encargados. Ellos son responsables del mantenimiento del lugar, pero también tienen la potestad de decidir el precio que se abona por el alquiler de una pieza o por el tiempo de permanencia. Son capaces de mediar en los conflictos que se den al interior, pueden permitir el ingreso a su antojo como el desalojo. En algunos casos, incluso firman papeles en nombre de los propietarios. Básicamente, son los administradores efectivos de los hoteles y es a ellos a quienes hay que caerles siempre bien. </p>

<p>Clara y Martín vivieron hace 4 años en el Hotel San José, un inmueble ubicado a tres cuadras de la plaza Constitución. En ese momento, cuentan, residían allí más de 200 personas. Hacía 6 años que estaban juntos, ella tenía 40, pelo negro, tez blanca y desde los 35 había empezado a perder la vista a causa de una enfermedad degenerativa que avanzó con rapidez durante la pandemia. A diferencia de la mayoría de las personas ciegas, Clara no veía sombras sino luz.</p>

<p>Las habitaciones más ostentosas del hotel familiar eran de 2 x 3 metros. Se vivía entre la incomodidad y el hacinamiento perfecto. Si cantabas suerte podías tener una pequeña ventana, dicen, aunque por eso el valor de la habitación se extendiera el doble.</p>

<p>El baño se compartía por piso y cada vez que Clara tenía que usarlo, Martín lo desinfectaba porque siempre estaba orinado. La vida en el hotel no era sencilla, había gritos y se vendía pasta base las 24 horas. Las habitaciones se caían a pedazos y se incendiaban cada dos por tres porque las instalaciones eléctricas eran precarias. El lugar no tenía habilitación, nadie pedía papeles para ingresar. Y quizás solo eso era una facilidad para ellos. En los últimos meses que vivieron allí, su situación habitacional se complicó: perdieron, por burocracia, el subsidio habitacional que el Gobierno de la Ciudad de Buenos Aires. Martín había llegado a un acuerdo con el encargado: haría el mantenimiento del lugar a cambio de una habitación donde quedarse. Después de algunas semanas decidió dejarlo. Se había cansado de arreglar algo que volvía a estar roto al día siguiente porque nadie cuidaba nada. El encargado lo despertaba a cualquier hora y lo tenía de “acá para allá”. La gota que rebalsó el vaso fue cuando le exigió que fuera él quien desalojara a la gente. Lo forzaron a entrar en la habitación de algunas personas que se habían demorado con el pago, mientras éstas no estaban, a empacar las pertenencias y a tirarlas a un contenedor de basura. “Para vivir así preferimos estar en la calle, yo botón no soy”.</p>

<h6 className={styles.span}>Ante la figura abstracta de los propietarios, emergen otros protagonistas: los encargados. Ellos son responsables del mantenimiento del lugar, pero también tienen la potestad de decidir el precio que se abona por el alquiler de una pieza o por el tiempo de permanencia.</h6>

<h3 className={styles.subTitle}>Un incendio sin testigos</h3>


<p>El humo salía negro por la ventana del último piso que daba a la calle Cochabamba, en Constitución. A. salió de la ducha, agarró una toalla, dos o tres pertenencias que vio a mano y bajó huyendo del lugar por una larga escalera hasta llegar a la primera esquina en la calle San José, casi debajo de la autopista. Era la primera vez que la habitación donde vivía se prendía fuego, aunque no era el primer hotel del barrio en el cual había vivido. Su vida lleva unos duros 42 años de los cuáles 11, los pasó privado de su libertad. Estaba cansado de la estigmatización, la marginalidad, la injusticia y el narcotráfico que le había quitado gran parte de su vida. Por eso –dice- desde que llegó al hotel de puertas verdes a mitad de la calle que acompaña en paralelo a la autopista, se ganó más enemigos que amigos. “Sabes que yo no compro con los narcos y ellos se sentían mal conmigo porque no podían someterme a sus caprichos de superioridad, yo creo que ellos, cuando estaba en la ducha, me tiraron algo dentro de la habitación. En ese mismo piso vivían también muchos de los que vendían cocaína y derivados, (se había peleado con ellos en varias ocasiones) pero abajo, en el piso intermedio, estaba Michael. De nacionalidad peruana, de unos 30 o 35 años, reducía y suministraba la droga a “los soldaditos” que trabajaban para él.</p>

<p>La comisaría correspondiente a la zona es la 1C, ubicada en la Av. San Juan al 1757. El comisario a cargo es Roque Gustavo Araoz. A pocas cuadras de allí, en San José 1224 (a la vuelta del hotel del cual A. tuvo que escaparse), hay un anexo. Cuando A. llegó a hacer la denuncia al día siguiente (la noche la pasó en el hospital a causa del humo inhalado), la policía no quiso tomarle declaración. Le dijo que el responsable no se encontraba y que tampoco había testigos de lo sucedido.</p>

<p>Las dudas acerca de si el incendio fue provocado o a causa de un desperfecto eléctrico por las instalaciones ilegales con las que cuenta el inmueble, para A. son pocas. De todas formas, no podrá confirmarlo porque a la policía –y a nadie más- le interesó indagar sobre aquello. A. tampoco podrá recuperar sus pertenencias pero de algo está seguro: el hotel del cual huyó forzosamente funciona como base de operaciones de una narco estructura que se hace cada vez más fuerte en el barrio de Constitución. Y –afirma- la connivencia policial es absoluta.</p>

<h6 className={styles.span}>Cuando A. llegó a hacer la denuncia al día siguiente (la noche la pasó en el hospital a causa del humo inhalado), la policía no quiso tomarle declaración. Le dijo que el responsable no se encontraba y que tampoco había testigos de lo sucedido.</h6>

<h3 className={styles.subTitle}>Hoteles y Estado, asunto unificado</h3>


<p>La relación estatal con los hoteles de Constitución data de varios años. Desde la década del ´80 han sido utilizados, bajo diferentes normativas y de diferentes formas, como política asistencial para la crisis emergente en materia habitacional. No solamente el GCBA los ha utilizado como lugares de residencia para personas de vulnerabilidad a lo largo del tiempo. En 2015, luego de que el Centro Socio Educativo de Régimen Cerrado “Dr. Luis Agote” cerrara debido a la muerte del adolescente de 17 años Diego Iván Borjas por un incendio en su celda, se creó un programa de articulación territorial coordinado por Susana Slamovich desde la Secretaría Nacional de Niñez, Adolescencia y Familia (Senaf), dependiente de Desarrollo Social de la Nación. Éste permitía que a aquellos que cumplían mayoría de edad dentro de los centros cerrados, no tenían donde ir y arrastraban problemas con la justicia, se les ofreciera asilo en una serie de hoteles.</p>

<p>Flavia Ruiz es psicóloga social y trabajó en este programa. Recuerda que el día del cumpleaños número 18 de Maximiliano lo acompañó desde el centro cerrado a un hotel ubicado en la calle Salta al 400. Al llegar, las habitaciones mugrientas de 2x2 y, al menos, 10 jóvenes más durmiendo en camas cuchetas. Duró menos de 2 meses, dice Flavia. Desapareció entre las sombras del barrio. Sospecha que fue reclutado para “alguna cuestión turbia” ya que “esas cosas pasan, sabemos que la policía recluta gente que está detenida y sola, para vender falopa o cometer otros delitos”.</p>

<p>En una de sus visitas al hotel, Flavia conoció al dueño, Omar. Por una compañera de trabajo se enteró luego de que no era solamente dueño de ese hotel sino el apoderado de seis más. Además, exmarido de la ya mencionada Susana Slamovich, coordinadora del programa para el que ella trabajaba. El programa duró un tiempo corto y cuando fue dado de baja, Slamovich pasó a ser la directora del Centro de Admisión y Derivación “Úrsula Llona de Inchausti”, ubicado a 3 cuadras del Congreso de la Nación.</p>

<h6 className={styles.span}>Hay una vinculación estrecha entre la gestión de drogas ilícitas, la precarización de la vida que eso genera (y en la cual se apoya para funcionar), y las políticas públicas para resolver la crisis habitacional que ha adoptado hasta aquí el GCBA.</h6>

<h3 className={styles.subTitle}>Un sistema al servicio del narco</h3>


<p>La complejidad de los hoteles familiares no puede entenderse sin pensar, también, en el rol de las fuerzas de seguridad en su entramado. Hay una vinculación estrecha entre la gestión de drogas ilícitas, la precarización de la vida que eso genera (y en la cual se apoya para funcionar), y las políticas públicas para resolver la crisis habitacional que ha adoptado hasta aquí el GCBA.</p>

<p>María de la Paz Toscani, autora de “Los hoteles pensión en la Ciudad de Buenos Aires”, destaca reiteradamente la vinculación que establecen las personas entrevistadas por ella en el barrio de Constitución con el accionar de la policía para “habilitar” las distintas actividades ilegales que se realizan en el barrio. Según los testimonios reunidos por la autora “el crecimiento de la venta de drogas acompañado por la instalación de cocinas, es posible a partir de la complicidad de la policía que obtiene una comisión para dejar libre el negocio”.</p>

<p>En consonancia con la información recabada en esta nota, Toscani asegura que “se han podido identificar hoteles pensión con actividades clandestinas e ilegales que -indistintamente de que fuesen hoteles legales o ilegales- se proponen diversificar su uso, más allá de la función residencial, con actividades ilegales que generan mayor rentabilidad para quienes regentean el lugar”. Entre los ejemplos, incluye la venta y la cocina de droga y la utilización de piezas como albergue transitorio o para ejercer la prostitución, situaciones que también fueron narradas por los vecinos a este cronista.</p>

<p>Si bien los hoteles familiares no se encuentran solamente en el barrio de Constitución, allí se han concentrado en su gran mayoría. Además del uso organizativo que significan para la estructura del narcotráfico, estos inmuebles representan un mercado de piezas en alquiler utilizadas indirectamente por el GCBA en medio de una crisis de vivienda que en la Ciudad Autónoma se vuelve cada vez más importante y transversal al conjunto de la sociedad. Incluso cuando una persona obtiene la ayuda económica, el mismo GCBA entrega un listado impreso de los hoteles legitimados a trabajar con el subsidio 690, listado que incluye a los mencionados a lo largo de esta investigación. Como si lo que pasa ahí no tuviera nada que ver con la gestión de la política. Como si no fuera una manera de legitimarlos.</p>
</>
)
};

export default Nota11