import styles from './TodasInvestigaciones.module.css';

const Nota14 = () => {
return(
<>
<div className={styles.NotaContainer} >

<p>Gabriel Mastrángelo sube a la autopista 25 de mayo con su motocicleta y acelera. Marcelo Garro, policía motorizado de la Ciudad de Buenos Aires, lo persigue desde atrás. Es 19 de noviembre de 2022 por la tarde y Gabriel solo quiere llegar a salvo a la próxima bajada. Unos minutos antes había agarrado una calle en contramano a la altura de Carlos Calvo y Lima. Tres efectivos motorizados lo abordaron con patadas e insultos cuando se detuvo. Gabriel, de una acelerada, los dejó atrás. Menos a Garro, que ahora no le pierde rastro encima de su BMW F 750. El velocímetro se dispara: 90 km. por hora; 100; 110. Ama las motos, Gabriel. Tiene 26 años, maneja desde los 12, su padre tenía un taller. La adrenalina de la velocidad, el viento que se filtra por el casco, el rugido del motor de su Honda Twistter que lo llena de paz. Pero ahora tiene a un policía a sus espaldas que, sin saberlo, desfunda su arma en plena autopista 25 de mayo. Garro, la reglamentaria en una mano, el volante en la otra, dispara tres veces. Dos balas pegan en la moto de Gabriel. La tercera en su cintura. Mastrángelo baja en la primera salida de la autopista y frena. El policía da la estocada final: lo choca, tirándolo al suelo. Sobre el pavimento, con una bala 
en su cuerpo, la pesadilla de Gabriel con la Motorizada no termina. Tampoco había empezado ese día.</p>


Pero ahora tiene a un policía a sus espaldas que, sin saberlo, desfunda su arma en plena autopista 25 de mayo. Garro, la reglamentaria en una mano, el volante en la otra, dispara tres veces. Dos balas pegan en la moto de Gabriel. La tercera en su cintura.</h6>

 

“Morite”, le decía el oficial</h3>

</p>En el año 2022, Gabriel trabajaba en una barbería por el barrio de Boedo. También militaba en el Movimiento Evita y colaboraba como profesor de fútbol en una escuelita para los más chicos en Balvanera. El 27 de agosto de ese año, volviendo a su casa en moto, encontró un celular en la esquina de San Juan y Combate de los Pozos. En un semáforo se cruzó a un policía motorizado. De moto a moto, él le explicó que halló un celular, que se lo quería entregar. El efectivo frenó, lo felicitó por su acción y le pidió que esperara. A la hora, quedó detenido por averiguación de antecedentes. “Tenía una causa de cuando era menor de edad. Me meten preso un año y medio en el penal de Ezeiza”, cuenta Gabriel en un café del barrio de Monserrat. “Estuve detenido ocho meses hasta que me dicen que voy a juicio. Después salgo absuelto, libre de culpa”, explica. Estuvo procesado hasta que se comprobó que la denuncia del dueño del celular era por extravío y no por robo. “Todo por querer devolverlo”, recuerda. “Salgo en 2022, quiero reamar mi vida y me pasa esto”.</p>

</p>“Esto”, es lo que le pasó aquel viernes 19 de noviembre de 2022 con la Policía Motorizada: la calle a contra mano, la persecución en la autopista, los tres disparos del oficial Marcelo Garro. “Había salido a hacer algunos deliverys con la moto de un amigo porque andaba mal de laburo”, recuerda. “Cuando me detienen por agarrar mal la calle Lima, me empiezan a insultar y a pegar patadas a la moto”, dice. “Me asusté y subí a la 25 de mayo. Después me dispararon”. Tras ser reducido, con una bala en el abdomen, al menos diez efectivos lo patearon en el piso. Gabriel escuchó que uno de los policías gritaba que él tenía un revolver. Las cámaras, luego, desmintieron a los uniformados. La práctica de la plantación de armas en la fuerza porteña contra pibes “sospechosos” es habitual. Solo basta repasar el caso de Lucas González, el joven asesinado por oficiales de civil de la Brigada de Investigaciones en Barracas en 2021, quienes quisieron ocultar el crimen haciendo pasar a su víctima como un criminal armado. Al respecto, puede leerse esta investigación del Mapa de la Policía.</p>

</p>Al llegar la ambulancia, las agresiones contra Gabriel continuaron. “Me subieron con insultos y golpes. Adentro me apretaban los brazos y las costillas. La paramédica les decía que me dejaran de tocar”, cuenta. Fue trasladado al Hospital Ramos Mejía, donde las amenazas policiales siguieron. Cuando su madre, Laura Pereyra, llegó al hospital, lo encontró inconsciente y esposado en una camilla, después lo llevaron a una habitación. Uno de los uniformados entró al cuarto y le empezó a apretar las costillas. “Morite”, le decía el oficial. Después, señala Gabriel, lo llevaron a otro cuarto, siempre custodiado por un policía de la Ciudad.</p>

</p>La familia denunció de forma pública las amenazas que recibieron, tanto ellos como Gabriel durante todo el tiempo en que permaneció internado. Lo acusaban, además, de haber robado la moto que manejaba cuando le dispararon. El hostigamiento siguió tras el cambio de cuarto e incluso, después de la cirugía de 4 horas que le practicaron para sacarle la bala. Cuando despertó, un sujeto enorme, vestido de civil y con una pistola en su cintura, estaba a su lado. “El chabón me decía ´a ver cómo te quedó la panza. Así vas a quedar por meterte con la policía. Más vale que no hagas denuncia´…”, relata Gabriel. Tras ser increpado por la familia, el hombre dijo llamarse Julián González, un oficial sin uniforme que se negó a mostrar identificación. Ese mismo día, después de la amenaza, volvió a su casa con una denuncia en su contra por resistencia a la autoridad por parte de la Motorizada y una colostomía temporal como consecuencia del disparo. Según el parte médico, las cuatro perforaciones que tenía intestino grueso requirieron que le cortaran 4 centímetros. La bala, que había rozado el recto, también le hizo dos perforaciones en el delgado.</p>

Tras ser reducido, con una bala en el abdomen, al menos diez efectivos lo patearon en el piso. Gabriel escuchó que uno de los policías gritaba que él tenía un revolver. Las cámaras, luego, desmintieron a los uniformados.</h6>

 

Escuadrones en las calles</h3>

</p>El cuerpo motorizado se creó en 1991 como un grupo especial de la Policía Federal Argentina (PFA). Hasta 2015, antes del traspaso de parte de la PFA a la extinta Policía Metropolitana, los pilotos se dedicaban más a los asuntos de tránsito, los cortes de calle, las movilizaciones, los traslados o los operativos en estadios de fútbol.
Desde 2017, con la creación de la Policía de la Ciudad, cada comisaría tiene sus pilotos que se limitan a su jurisdicción. Los de la División, sin embargo, se mueven según el Mapa del Delito. En total, el Gobierno de la Ciudad de Buenos Aires (GCBA) estima que son entre 100 y 120 motos por día las que recorren la ciudad y detienen, en promedio, entre cuatro y cinco personas –presuntos delincuentes- por jornada. Según se afirma en el sitio web oficial del GCBA, cada piloto conduce durante 12 horas por día patrullando las calles. No hacen controles estáticos, sino que “las motos están siempre en movimiento”. Formar un piloto para esa División, explica el gobierno porteño, implica un año de trabajo. Deben realizar un curso en el Instituto Superior de Seguridad Pública, así como también distintas capacitaciones anuales. Es un cuerpo que cuenta siempre “con un alto número de lesionados, fundamentalmente por el 'modus operandi' que caracteriza a los llamados ´motochorros´, a quienes no suele importarles el riesgo de una colisión cuando comenten este tipo de delitos”.</p>

</p>Dentro del Departamento del Cuerpo de la Policía Motorizada se diferencian dos escuadrones. Por un lado, la “Motorizada”, que incluye ─entre otros─ al servicio especial de tránsito, en donde trabajaba Garro. Y en otro el “Motorizado táctico”, con el grupo de acción y unidades de detención. De estos últimos, se desprenden el Grupo de Acción Motorizada (GAM) y el Despliegue de Intervenciones Rápidas (DIR). “El GAM suele ser un ‘cazador’ de manifestantes durante las protestas callejeras”, señala María del Carmen Verdú, abogada de la Coordinadora contra la Represión Policial e Institucional (Correpi). “También tienen personal en las Comisarías Comunales y Vecinales, los que operan el sistema de Video Vigilancia y Anillo Digital y el Comando y Control de la Dirección de Gestión de Emergencias Policiales”, agrega. La titular de Correpi destaca, por otro lado, su dinámica de acción: “tienen una lógica bélica de intervención, al estilo de las BRI (Brigadas de Rápida Intervención) de la vieja Metropolitana”.</p>

En total, el Gobierno de la Ciudad de Buenos Aires  estima que son entre 100 y 120 motos por día las que recorren la ciudad y detienen, en promedio, entre cuatro y cinco personas –presuntos delincuentes- por jornada.</h6>

 

Las piruetas de un tirador</h3>
 
</p>El Hospital Ramos Mejía, donde estuvo internado Gabriel, está a tres cuadras del Departamento del Cuerpo de la Policía Motorizada que funciona en avenida Belgrano N° 3106. En el lugar  -un galpón de casi media manzana con un portón de hierro en la entrada- las motos salen y entran permanentemente. El oficial Marcelo Garro, hoy apartado de su cargo, y que se desempeñaba en el servicio especial de tránsito de esa fuerza, quizás atravesaba ese portón todos los días. “Está desafectado y a la espera de un juicio”, explica de forma escueta el abogado de Gabriel, Martín Herrera, con quien no se pudo coordinar una vista del expediente a los fines de la presente investigación. Según las denuncias e información recibida en el Mapa de la Policía, la misma fuerza que disparó, golpeó y amedrentó a Gabriel, se encargó también de limpiar toda la zona de los hechos sin dejar casquillos de balas en la calle. Es decir, la única evidencia del tiroteo se encuentra alojada en la pierna de Gabriel, a la espera de una nueva cirugía.</p>

</p>Entre los oficiales investigados se señala, asimismo, a Pablo César Ríos como participante en la persecución, quien pertenece junto a Garro a la Segunda Compañía de la División Servicios Especiales de Tránsito del Departamento Policía Motorizada. Herrera, abogado de Mastrángelo, confirmó al respecto que el oficial Garro había integrado, previamente, el escuadrón de piruetas motorizadas Brigada Blanca. Se trata de un equipo de oficiales expertos en el manejo de motocicletas que hacen eventos demostrativos en diferentes actos públicos. “Era un tirador hábil por eso”, señaló. “Tenía facilidades para manejar”.</p>

Se señala a Pablo César Ríos como participante en la persecución, quien pertenece junto a Marcelo Garro a la Segunda Compañía de la División Servicios Especiales de Tránsito del Departamento Policía Motorizada</h6>

 

“Mirá si me buscan a mí después”</h3>

</p>“Ni bien nos enteramos, fuimos muchos militantes a acompañar a Gabi”, recuerda Carolina Díaz, trabajadora social e integrante del Movimiento Evita. “La misma fuerza que le había disparado era la que lo custodiaba en el hospital. Un horror”, dice. El 26 de noviembre de 2022, a una semana del ataque y tras las amenazadas recibidas por Gabriel, el Evita marchó hacia la sede de la motorizada junto a familiares y amigos. “Siempre fue fundamental el acompañamiento a los pibes que sufrieron violencia institucional en nuestro espacio. Nos atravesó mucho la situación de Jon Camafreitas, un pibe que la federal mató y era nieto de una compañera nuestra”, recuerda. El 21 de enero del 2012, Camafreitas, de 18 años, fue asesinado de un disparo en la cabeza por un policía federal en el barrio de Boedo, tras ser detenido en medio de una discusión  con otros jóvenes. Durante cuatro días, el adolescente agonizó en el mismo hospital donde estuvo Gabriel. “Muchas de nuestras compañeras son familiares de Camafreitas”, cuenta la militante. “En Balvanera y otros barrios de la capital los pibes que andan en moto con determinada ropa y corte de pelo, son hostigados por la Motorizada”. El miedo que esto produce en los jóvenes para hacer una denuncia, continúa Carolina, es tajante. “Mirá si me buscan a mí después”, es el testimonio que escucha de muchos pibes, cansados de ser el blanco de los hostigamientos.</p>

</p>¿Cómo se desarma ese entramado de impunidad? Para María Victoria Pita, investigadora del Conicet y del Equipo de Antropología Política y Jurídica en el Instituto de Ciencias Antropológicas de Filosofía y Letras de la Universidad de Buenos Aires, hay una articulación muy aceitada entre la Policía y el Poder Judicial de la Ciudad que lo nutre. “El blindaje a la fuerza porteña, salvo algunos casos excepcionales, está muy marcado. No solo hay que prestar atención a los desempeños policiales y el uso desproporcionado de su fuerza, sino también a las formas de intervención del resto de los poderes”, señala.</p>

</p>El patrón de las víctimas que sufren el hostigamiento de oficiales porteños, continúa la especialista, también responde a una conducta institucionalizada. “La tradición de prácticas abusivas especialmente con jóvenes de la zona sur de la ciudad, que incluye a vecinos de barrios populares y villas, es muy común”, destaca Pita. “Es una distribución desigual de la fuerza a través de un control donde componentes como el indicio o la sospecha son lo único que impera”. La desigualdad que señala surge de los datos del informe de la Secretaría Letrada contra la Violencia Institucional del Ministerio Público Fiscal de la Ciudad del año 2022. La Comuna 1, indica el informe, que comprende a barrios del sur como Monserrat ─donde Gabriel fue baleado─ recibió la mayor cantidad de denuncias por abuso policial. Fueron 475. La edad promedio de esas víctimas era de 33 años.</p>

</p>“No voy a dejar de subirme a una moto por lo que me hicieron”, dice Gabriel frente a las canchitas de la escuela de fútbol del Movimiento Evita en Balvanera. “Es una herramienta de trabajo. Tengo muchos amigos que laburan con la moto y los de la Motorizada los viven verdugueando”. Dice que le puso nombre a todas las que tuvo “quizás es porque a veces anduve solo y la moto era lo único que tenía”. Ahora, cuenta, tiene una Zanella. Le puso kikachi. “Uno decide para qué usa la moto. Si para cosas buenas o malas y ahí aparecen las injusticias. Porque uno no puede andar rápido con su moto que te quieren bajar de un disparo”, dice y se hunde en el silencio.</p>
</>
);
}

export default Nota14;